Configured Allure reports

diff --git a/.github/workflows/test_in_windows.yaml b/.github/workflows/test_in_windows.yaml
--- a/.github/workflows/test_in_windows.yaml
+++ b/.github/workflows/test_in_windows.yaml
@@ -47,42 +47,104 @@ jobs:
           mkdir Screenshots
         shell: cmd
 
-      - name: Execute Tests
-        shell: pwsh
-        run: |
-          pytest Tests -v -s `
-            --junitxml=Reports/test-results.xml `
-            --html=Reports/report.html `
-            --self-contained-html
+      # - name: Execute Tests
+      #   shell: pwsh
+      #   run: |
+      #     pytest Tests -v -s `
+      #       --junitxml=Reports/test-results.xml `
+      #       --html=Reports/report.html `
+      #       --self-contained-html
 
-          echo "PYTEST_EXIT_CODE=$LASTEXITCODE" >> $env:GITHUB_ENV
+      #     echo "PYTEST_EXIT_CODE=$LASTEXITCODE" >> $env:GITHUB_ENV
+      #   continue-on-error: true
+
+      # - name: Upload HTML Report
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: html-report
+      #     path: Reports/report.html
+
+      # - name: Upload JUnit Results
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: junit-results
+      #     path: Reports/test-results.xml
+
+      # - name: Upload Screenshots
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: failure-screenshots
+      #     path: Screenshots/
+
+      # - name: Fail Workflow If Tests Failed
+      #   shell: pwsh
+      #   run: |
+      #     if ($env:PYTEST_EXIT_CODE -ne 0) {
+      #         Write-Host "One or more tests failed."
+      #         exit 1
+      #     }
+
+      - name: Execute Tests
+        run: |
+          pytest Tests -v --alluredir=allure-results
         continue-on-error: true
 
-      - name: Upload HTML Report
-        if: always()
+      - name: Upload Allure Results
         uses: actions/upload-artifact@v4
-        with:
-          name: html-report
-          path: Reports/report.html
-
-      - name: Upload JUnit Results
         if: always()
-        uses: actions/upload-artifact@v4
         with:
-          name: junit-results
-          path: Reports/test-results.xml
+          name: allure-results
+          path: allure-results
 
-      - name: Upload Screenshots
-        if: always()
-        uses: actions/upload-artifact@v4
+  allure:
+    needs: test
+
+    runs-on: ubuntu-latest
+
+    permissions:
+      contents: write
+      pages: write
+      id-token: write
+
+    steps:
+
+      - uses: actions/checkout@v4
+
+      - name: Download Allure Results
+        uses: actions/download-artifact@v4
         with:
-          name: failure-screenshots
-          path: Screenshots/
+          name: allure-results
+          path: allure-results
 
-      - name: Fail Workflow If Tests Failed
-        shell: pwsh
-        run: |
-          if ($env:PYTEST_EXIT_CODE -ne 0) {
-              Write-Host "One or more tests failed."
-              exit 1
-          }
+      - name: Generate Allure Report
+        uses: simple-elf/allure-report-action@master
+        with:
+          allure_results: allure-results
+          allure_report: allure-report
+
+      - name: Upload GitHub Pages Artifact
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: allure-report
+
+  deploy:
+    needs: allure
+
+    runs-on: ubuntu-latest
+
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+
+    permissions:
+      pages: write
+      id-token: write
+
+    steps:
+
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
